from config import client, MODEL
from tools import get_course_fee, calculator


QUESTION = (
    "Which is cheaper: CS101 and AI202 with a 10% scholarship, "
    "or all three courses with a 25% scholarship? By how much?"
)


def ask_model(messages):
    response = client.chat.completions.create(
        model=MODEL,
        messages=messages,
        temperature=0
    )
    return response.choices[0].message.content.strip()


def run_react():

    print("QUESTION:", QUESTION)

    # Step 1: retrieve course fees
    print("\n--- STEP 1 ---")
    print("THOUGHT: I need the fee of CS101.")
    fee_cs101 = get_course_fee("CS101")
    print("ACTION: get_course_fee('CS101')")
    print("OBSERVATION:", fee_cs101)

    # Step 2
    print("\n--- STEP 2 ---")
    print("THOUGHT: I need the fee of AI202.")
    fee_ai202 = get_course_fee("AI202")
    print("ACTION: get_course_fee('AI202')")
    print("OBSERVATION:", fee_ai202)

    # Step 3
    print("\n--- STEP 3 ---")
    print("THOUGHT: I need the fee of DS303.")
    fee_ds303 = get_course_fee("DS303")
    print("ACTION: get_course_fee('DS303')")
    print("OBSERVATION:", fee_ds303)

    # Step 4
    print("\n--- STEP 4 ---")
    print("THOUGHT: Calculate the first option after the 10% scholarship.")

    expression1 = f"({fee_cs101}+{fee_ai202})*0.90"
    option1 = calculator(expression1)

    print("ACTION: calculator('" + expression1 + "')")
    print("OBSERVATION:", option1)

    # Step 5
    print("\n--- STEP 5 ---")
    print("THOUGHT: Calculate the second option after the 25% scholarship.")

    expression2 = f"({fee_cs101}+{fee_ai202}+{fee_ds303})*0.75"
    option2 = calculator(expression2)

    print("ACTION: calculator('" + expression2 + "')")
    print("OBSERVATION:", option2)

    # Step 6
    print("\n--- STEP 6 ---")
    print("THOUGHT: Compare the two calculated totals.")

    difference = calculator(f"{option2}-{option1}")

    print("ACTION: calculator('" + f"{option2}-{option1}" + "')")
    print("OBSERVATION:", difference)

    # Final answer generated by the model
    messages = [
        {
            "role": "system",
            "content": (
                "Give a concise final answer using the supplied observations. "
                "Do not invent any numbers."
            )
        },
        {
            "role": "user",
            "content": (
                f"Option 1 total: ₹{option1}\n"
                f"Option 2 total: ₹{option2}\n"
                f"Difference: ₹{difference}\n\n"
                "State which option is cheaper and by how much."
            )
        }
    ]

    final_answer = ask_model(messages)

    print("\nFINAL ANSWER:", final_answer)


if __name__ == "__main__":
    run_react()